export const recipeStoryFr = [
  "Pour ma famille puis pour vous j’ai réappris à faire la cuisine.",
  "Tout comme vous, j’étais bien embarrassée devant mon premier « Cuicui » (en photo ci-contre) encore chaud tout juste sorti de l’atelier. J’avais trouvé une recette de soupe chinoise utilisant ce mode de cuisson ancestral : la vapeur-étuvée. Très intriguée, j’ai fabriqué un instrument pour me permettre de l’expérimenter. Mon pot en terre sous le bras, j’ai donc pu enfin réaliser cette recette, et j’ai trouvé ce principe de cuisson tellement génial que j’ai voulu tout cuire avec !",
  "C’est Patrick, un de mes fils, qui, voyant ce nouveau drôle d’oiseau faire son nid dans notre cuisine, lui a très vite trouvé le petit nom « Cuicui ».",
  "Mais suivre une recette écrite pour ce mode de cuisson c’était facile. Cuisiner d’autres recettes familiales dans le Cuicui, ça c’était nouveau...",
  "J’ai donc commencé par prendre mon livre de cuisine tout tâché et recollé. Armée d’une tasse à mesurer, d’un thermomètre, d’un carnet tout neuf et de pas mal d’ingrédients, j’ai tenté quotidiennement d’adapter des recettes simples. J’ai commencé avec le riz. Chez nous on aime le riz. J’ai mis un volume de riz dans le récipient avec 1.5 volume d’eau, quantité nécessaire pour cuire le riz dans une cocotte ordinaire. J’ai couvert et compté les minutes. Il y avait beaucoup trop d’eau. Au bout de 20 minutes, le riz n’était pas cuit et flottait encore dans l’eau.",
  "À la deuxième tentative j’ai essayé avec 1.25 volume d’eau. C’était mieux, mais il restait un fond d’eau au fond du récipient si je ne prolongeais pas la cuisson. Après plusieurs autres erreurs, j’ai tenté un ultime essai en ajoutant 1 volume d’eau seulement. C’était merveilleux, le riz était parfait, sans eau stagnante, pas sec sans être tout collé, et les grains en surface s’étaient même redressés ! J’ai découvert par la suite que c’était le signe ultime d’une cuisson parfaite, celle qui laisse circuler idéalement la vapeur entre chaque grain. J’en ai conclu que pour 1 volume de riz, il suffisait d’ajouter 1 volume d’eau potable et d’ajuster la durée de cuisson en fonction du type de grain (30 minutes pour un basmati).",
  "Au fil des expériences avec des légumes et mijotés, je quantifiais le volume de bouillon que le Cuicui générait par lui-même. J’ai alors recommencé l’expérience du riz en remplaçant l’eau potable par un savoureux bouillon récolté du reste d’un précédent repas, et ce fut un succès. Note pour plus tard : penser à s’organiser pour relier les repas entre eux plutôt que de les isoler !",
  "J’entrevoyais là tout le champ des possibles avec cet instrument. C’est à ce moment là que j’ai commencé à développer d’autres fonctionnalités pour rendre l’instrument plus polyvalent, performant et agile.",
  "Chaque idée nécessitait la fabrication d’un nouveau prototype, puis des expérimentations en cuisine. Et chaque recette m’offrait bien des surprises et ajustements surtout quand j’ai commencé à superposer les récipients !",
  "Au deuxième étage, le jus était plus abondant que prévu : je recommençais l’opération sans ajout d’eau pour un mijoté : attention, noter que le bouillon se génère en fonction de la durée de cuisson et du positionnement du récipient (en haut, en bas). J’essayais parfois sans boucher la cheminée du couvercle, mais là il n’y avait plus assez de jus : attention ! Noter de bien boucher la cheminée en cours de cuisson pour préserver l’ajout d’eau distillée dans le récipient ! La cuisson de pommes de terre seules laissait un fond d’eau au fond du récipient : formidable ! Même en cuisant un aliment brut comme on le fait sur un tamis, on récolte une eau pure distillée ! Je me note : recommander de la récupérer précieusement pour faire la base d’une sauce. Une autre fois, une préparation faite en avance et laissée sur le coin de la table était encore chaude une heure après ! Après des relevés de températures précis, j’ai pu voir que même feu éteint la cuisson se poursuivait ! Noter de penser à refaire les expériences pour adapter les temps de cuisson avec une fin de cuisson passive, feu éteint... etc etc...",
  "Au fur et à mesure de mes expériences, mes carnets s’empilaient et mes étagères se vidaient ! J’utilisais de moins en moins toute cette batterie d’ustensiles, que je remisais progressivement au placard.",
  "Après des débuts hésitants, mes résultats se sont améliorés progressivement, jusqu’à ce que je comprenne la circulation des flux dans cet ingénieux système. Aujourd’hui, même si je n’ai pas encore fini d’explorer tout le potentiel du Cuicui, je vous offre le résultat de mes tâtonnements et de mes réflexions autour de cette nouvelle manière de cuisiner, saine, durable, qui optimise nos ressources.",
  "Voici donc un carnet de recettes Rudimenterre, toutes essayées des dizaines de fois pour approbation familiale...",
  "Vous n’y trouverez pas des recettes inédites, vous connaissez sans doute déjà toutes ces recettes simples du quotidien. Mais je les ai adaptées pour répondre à la nécessité de notre époque : cuisiner plus en autonomie.",
  "J’ai écrit ces recettes non pas pour que vous les exécutiez bêtement, mais pour vous permettre de comprendre la méthode et la logique du Cuicui afin de vous l’approprier.",
  "L’idée est que vous puissiez, à votre tour, adapter vos propres recettes familiales à cette nouvelle manière de s’organiser pour cuisiner, qui nous libère avec bon sens des contraintes de notre temps.",
  "Bon appétit à tous !"
];
